# Generated by Django 5.1.1 on 2024-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("artist", models.CharField(max_length=50)),
                ("duration", models.FloatField()),
                ("last_play", models.DateTimeField()),
            ],
        ),
    ]
